<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <PackageIcon></PackageIcon>
    <RepositoryUrl>https://github.com/Mahdikhoubrouy/CastleSharp</RepositoryUrl>
    <PackageTags>TelegramBot,Telegram,Bot,TelegramTools,Tools,CastleSharp</PackageTags>
    <FileVersion>3.0.0</FileVersion>
    <AssemblyVersion>3.0.0</AssemblyVersion>
	<Version>3.0.0</Version>
    <PackageReleaseNotes>Add Filter Attribute</PackageReleaseNotes>
    <Title>CastleSharp</Title>
    <PackageId>CastleSharp</PackageId>
    <Authors>Mahdi Khoubrouy</Authors>
    <Product>CastleSharp</Product>
    <Description>a tool for telegram.bot </Description>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Telegram.Bot" Version="[19.*,)" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Properties\" />
  </ItemGroup>

</Project>
